import pytest
from alembic import command
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

from scripts import pgtools
from tests.conftest import ROOT, alembic_config

VERSIONS = ROOT / "alembic" / "versions"
BASELINE = VERSIONS / "0001_postgresql_baseline.py"
DOMAIN_TABLES = {
    "users",
    "suppliers",
    "contracts",
    "contract_amendments",
    "invoices",
    "documents",
    "validation_results",
    "audit_logs",
    "login_attempts",
    "reviews",
    "user_sessions",
}


@pytest.fixture()
def empty_db():
    """Base PostgreSQL vacia, adicional a la de la sesion; se elimina al terminar la prueba."""
    with pgtools.temporary_database("portal_test_mig_") as url:
        yield pgtools.url_string(url)


def query(url: str, sql: str) -> list:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            return connection.execute(text(sql)).all()
    finally:
        engine.dispose()


def tables(url: str) -> set[str]:
    return {name for (name,) in query(url, "SELECT tablename FROM pg_tables WHERE schemaname = 'public'")}


def test_upgrade_head_coincide_con_los_modelos(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, "head")
    command.check(config)  # lanza AutogenerateDiffsDetected si modelos y migraciones difieren
    assert tables(empty_db) == DOMAIN_TABLES | {"alembic_version"}


def test_downgrade_de_la_revision_base_no_destruye_datos(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, "head")
    before = tables(empty_db)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, "base")
    assert tables(empty_db) == before
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [("0001_postgresql_baseline",)]


def test_revisiones_explicitas_sin_create_all_ni_modelos():
    revisions = list(VERSIONS.glob("*.py"))
    assert revisions
    for revision in revisions:
        source = revision.read_text(encoding="utf-8")
        for forbidden in ("create_all", "drop_all", "app.models"):
            assert forbidden not in source, f"{revision.name} contiene {forbidden}"


def test_revision_base_explicita_para_postgresql():
    source = BASELINE.read_text(encoding="utf-8")
    assert source.count("op.create_table(") == len(DOMAIN_TABLES)
    for forbidden in ("pragma", "sqlite"):
        assert forbidden not in source.lower()
    legacy = ("0001_initial", "0004_integridad_datos", "0006_user_sessions")
    assert not [name for name in legacy if (VERSIONS / f"{name}.py").exists()], "la cadena anterior debe retirarse"
