import pytest
from alembic import command
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.pool import NullPool

from scripts import pgtools
from tests.conftest import ROOT, alembic_config, head_revision

VERSIONS = ROOT / "alembic" / "versions"
BASELINE = VERSIONS / "0001_postgresql_baseline.py"
DOMAIN_TABLES = {
    "users",
    "suppliers",
    "contracts",
    "contract_amendments",
    "invoices",
    "documents",
    "validation_results",
    "audit_logs",
    "login_attempts",
    "reviews",
    "user_sessions",
    "invoice_document_types",
    "notification_templates",
    "notification_mailboxes",
    "notification_copies",
    "email_deliveries",
}
NOTIFICATION_TABLES = {"notification_mailboxes", "notification_copies", "email_deliveries"}
BASELINE_TABLES = DOMAIN_TABLES - {"invoice_document_types", "notification_templates"} - NOTIFICATION_TABLES


@pytest.fixture()
def empty_db():
    """Base PostgreSQL vacia, adicional a la de la sesion; se elimina al terminar la prueba."""
    with pgtools.temporary_database("portal_test_mig_") as url:
        yield pgtools.url_string(url)


def query(url: str, sql: str) -> list:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.connect() as connection:
            return connection.execute(text(sql)).all()
    finally:
        engine.dispose()


def tables(url: str) -> set[str]:
    return {name for (name,) in query(url, "SELECT tablename FROM pg_tables WHERE schemaname = 'public'")}


def test_upgrade_head_coincide_con_los_modelos(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, "head")
    command.check(config)  # lanza AutogenerateDiffsDetected si modelos y migraciones difieren
    assert tables(empty_db) == DOMAIN_TABLES | {"alembic_version"}


def test_downgrade_de_la_revision_base_no_destruye_datos(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, "head")
    before = tables(empty_db)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, "base")
    assert tables(empty_db) == before
    # Toda la corrida es una transaccion: el fallo de la base revierte tambien los downgrades posteriores.
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [(head_revision(),)]


def test_revisiones_explicitas_sin_create_all_ni_modelos():
    revisions = list(VERSIONS.glob("*.py"))
    assert revisions
    for revision in revisions:
        source = revision.read_text(encoding="utf-8")
        for forbidden in ("create_all", "drop_all", "app.models"):
            assert forbidden not in source, f"{revision.name} contiene {forbidden}"


def test_revision_base_explicita_para_postgresql():
    source = BASELINE.read_text(encoding="utf-8")
    assert source.count("op.create_table(") == len(BASELINE_TABLES)
    for forbidden in ("pragma", "sqlite"):
        assert forbidden not in source.lower()
    legacy = ("0001_initial", "0004_integridad_datos", "0006_user_sessions")
    assert not [name for name in legacy if (VERSIONS / f"{name}.py").exists()], "la cadena anterior debe retirarse"


BULK_IMPORT = "0002_supplier_bulk_import"
SUPPLIER_COLUMNS = (
    "business_name, supplier_type, email, status, confidentiality_agreement, economic_proposal, created_at, updated_at"
)


NATIONAL_COLUMNS, NATIONAL_VALUES = "origin, country, rfc", "'NATIONAL', 'MX', 'MIG200101AB1'"


def execute(url: str, sql: str) -> None:
    engine = create_engine(url, poolclass=NullPool)
    try:
        with engine.begin() as connection:
            connection.execute(text(sql))
    finally:
        engine.dispose()


def insert_supplier(url: str, extra_columns: str = "rfc", extra_values: str = "'MIG200101AB1'", status="ACTIVE"):
    execute(
        url,
        f"INSERT INTO suppliers ({SUPPLIER_COLUMNS}, {extra_columns}) VALUES "
        f"('Proveedor previo', 'PERSONA_MORAL', 'previo@proveedor.mx', '{status}', false, false, now(), now(), "
        f"{extra_values})",
    )


def supplier_columns(url: str) -> set[str]:
    rows = query(url, "SELECT column_name FROM information_schema.columns WHERE table_name = 'suppliers'")
    return {name for (name,) in rows}


def test_proveedores_previos_quedan_nacionales(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, "0001_postgresql_baseline")
    insert_supplier(empty_db)
    command.upgrade(config, BULK_IMPORT)
    assert query(empty_db, "SELECT origin, country, rfc, foreign_tax_id, status FROM suppliers") == [
        ("NATIONAL", "MX", "MIG200101AB1", None, "ACTIVE")
    ]


def test_downgrade_de_carga_masiva_sin_datos_nuevos(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, BULK_IMPORT)
    insert_supplier(empty_db, NATIONAL_COLUMNS, NATIONAL_VALUES)
    command.downgrade(config, "0001_postgresql_baseline")
    assert not {"origin", "foreign_tax_id", "country"} & supplier_columns(empty_db)
    assert query(empty_db, "SELECT rfc, status FROM suppliers") == [("MIG200101AB1", "ACTIVE")]
    command.upgrade(config, "head")
    command.check(config)


@pytest.mark.parametrize(
    ("extra_columns", "extra_values", "status"),
    [
        ("origin, foreign_tax_id, country", "'INTERNATIONAL', '12-3456789', 'US'", "ACTIVE"),
        (NATIONAL_COLUMNS, NATIONAL_VALUES, "REGISTERED"),
    ],
)
def test_downgrade_de_carga_masiva_con_datos_nuevos(empty_db, extra_columns, extra_values, status):
    config = alembic_config(empty_db)
    command.upgrade(config, BULK_IMPORT)
    insert_supplier(empty_db, extra_columns, extra_values, status)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, "0001_postgresql_baseline")
    assert {"origin", "foreign_tax_id", "country"} <= supplier_columns(empty_db)
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [(BULK_IMPORT,)]


DOCUMENT_TYPES = "0003_invoice_document_types"
# Catalogo inicial (HU-04): clave -> (nombre, formatos, nacional, internacional).
INITIAL_CATALOG = {
    "INVOICE_XML": ("XML del CFDI", ["XML"], "REQUIRED", "NOT_APPLICABLE"),
    "INVOICE_PDF": ("PDF del CFDI", ["PDF"], "REQUIRED", "NOT_APPLICABLE"),
    "FOREIGN_INVOICE": ("Invoice (PDF)", ["PDF"], "NOT_APPLICABLE", "REQUIRED"),
    "PURCHASE_ORDER": ("Orden de compra", ["PDF", "PNG", "JPEG", "TXT"], "REQUIRED", "REQUIRED"),
    "APPROVAL": ("Vo.Bo. del líder de proyecto", ["PDF", "PNG", "JPEG", "TXT"], "REQUIRED", "REQUIRED"),
    "CONTRACT": ("Contrato", ["PDF", "PNG", "JPEG", "TXT"], "OPTIONAL", "OPTIONAL"),
    "CONTRACT_ANNEX": ("Anexo del contrato", ["PDF", "PNG", "JPEG", "TXT"], "OPTIONAL", "OPTIONAL"),
    "PAYMENT_COMPLEMENT_XML": ("Complemento de pago (XML)", ["XML"], "OPTIONAL", "NOT_APPLICABLE"),
    "PAYMENT_COMPLEMENT_PDF": ("Complemento de pago (PDF)", ["PDF"], "OPTIONAL", "NOT_APPLICABLE"),
    "ADDITIONAL": ("Documentación adicional", ["PDF", "PNG", "JPEG", "XML", "TXT"], "OPTIONAL", "OPTIONAL"),
}


def insert_invoice_documents(url: str, *document_types: str) -> None:
    """Un usuario, un proveedor nacional, una factura y un documento vigente por tipo."""
    insert_supplier(url, NATIONAL_COLUMNS, NATIONAL_VALUES)
    execute(
        url,
        "INSERT INTO users (name, email, password_hash, role, is_active, created_at) "
        "VALUES ('Previo', 'previo@poc.local', 'x', 'PROVIDER', true, now())",
    )
    execute(
        url,
        "INSERT INTO invoices (internal_folio, supplier_id, uploaded_by, invoice_number, service_period, project_name,"
        " subtotal, tax, total, currency, status, created_at) SELECT 'FAC-MIG-1', s.id, u.id, 'MIG-1', '08/2026',"
        " 'Proyecto', 0, 0, 0, 'MXN', 'DRAFT', now() FROM suppliers s, users u",
    )
    for document_type in document_types:
        execute(
            url,
            "INSERT INTO documents (invoice_id, supplier_id, document_type, original_filename, stored_filename, path,"
            " mime_type, file_size, sha256, uploaded_at, uploaded_by, processing_status, is_current)"
            f" SELECT i.id, i.supplier_id, '{document_type}', 'a.pdf', 'a.pdf', 'invoices/1/a.pdf', 'application/pdf',"
            " 1, repeat('0', 64), now(), i.uploaded_by, 'PROCESSED', true FROM invoices i",
        )


def catalog(url: str) -> dict:
    rows = query(
        url,
        "SELECT code, name, formats, national_requirement, international_requirement, is_system, is_active"
        " FROM invoice_document_types ORDER BY id",
    )
    return {code: rest for code, *rest in rows}


def test_catalogo_inicial_tras_la_migracion(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, BULK_IMPORT)
    insert_invoice_documents(empty_db, "INVOICE_XML", "PURCHASE_ORDER", "TAX_STATUS")
    command.upgrade(config, DOCUMENT_TYPES)
    loaded = catalog(empty_db)
    assert list(loaded) == list(INITIAL_CATALOG), "los tipos del sistema se siembran en el orden del catalogo"
    assert loaded == {code: [*values, True, True] for code, values in INITIAL_CATALOG.items()}
    assert query(empty_db, "SELECT document_type FROM documents ORDER BY id") == [
        ("INVOICE_XML",),
        ("PURCHASE_ORDER",),
        ("TAX_STATUS",),
    ]


def test_downgrade_del_catalogo_sin_datos_nuevos(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, DOCUMENT_TYPES)
    execute(empty_db, "UPDATE invoice_document_types SET national_requirement = 'OPTIONAL' WHERE code = 'CONTRACT'")
    command.downgrade(config, BULK_IMPORT)
    assert "invoice_document_types" not in tables(empty_db)
    command.upgrade(config, "head")
    command.check(config)


@pytest.mark.parametrize("data", ["support_type", "FOREIGN_INVOICE", "SOPORTE_12"])
def test_downgrade_del_catalogo_con_datos_nuevos(empty_db, data):
    config = alembic_config(empty_db)
    command.upgrade(config, DOCUMENT_TYPES)
    if data == "support_type":
        execute(
            empty_db,
            "INSERT INTO invoice_document_types (code, name, formats, is_system, is_active, national_requirement,"
            " international_requirement, created_at, updated_at) VALUES ('SOPORTE_11', 'Reporte de horas', '{PDF}',"
            " false, false, 'NOT_APPLICABLE', 'NOT_APPLICABLE', now(), now())",
        )
    else:
        insert_invoice_documents(empty_db, data)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, BULK_IMPORT)
    assert "invoice_document_types" in tables(empty_db)
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [(DOCUMENT_TYPES,)]


NOTIFICATION_TEMPLATES = "0004_notification_templates"


def test_instalacion_nueva_con_las_plantillas_predeterminadas(empty_db):
    from app.services.notification_templates import EVENTS

    command.upgrade(alembic_config(empty_db), "head")
    rows = query(empty_db, "SELECT event, subject, body, version, updated_by FROM notification_templates ORDER BY id")
    # La migracion copia los textos (no importa app): deben coincidir con el catalogo del servicio.
    assert rows == [(event.value, spec.default_subject, spec.default_body, 1, None) for event, spec in EVENTS.items()]


def test_downgrade_de_plantillas_sin_cambios(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, NOTIFICATION_TEMPLATES)
    command.downgrade(config, DOCUMENT_TYPES)
    assert "notification_templates" not in tables(empty_db)
    command.upgrade(config, "head")
    command.check(config)


def test_downgrade_de_plantillas_modificadas(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, NOTIFICATION_TEMPLATES)
    execute(
        empty_db,
        "UPDATE notification_templates SET subject = 'Otro {{numero_factura}}', version = 2"
        " WHERE event = 'INVOICE_REJECTED'",
    )
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, DOCUMENT_TYPES)
    assert "notification_templates" in tables(empty_db)
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [(NOTIFICATION_TEMPLATES,)]


NOTIFICATION_RECIPIENTS = "0005_notification_recipients"


def test_instalacion_nueva_con_el_buzon_de_recepcion(empty_db):
    command.upgrade(alembic_config(empty_db), "head")
    assert query(empty_db, "SELECT code, name, addresses, updated_by FROM notification_mailboxes") == [
        ("INVOICE_RECEPTION", "Recepción de Facturas", ["recepcionfacturas@ultrasist.com.mx"], None)
    ]
    copies = query(empty_db, "SELECT event, addresses, updated_by FROM notification_copies ORDER BY id")
    events = ["INVOICE_AUTHORIZED", "INVOICE_REJECTED", "INVOICE_OBSERVATIONS", "INVOICE_CANCELLED"]
    assert copies == [(event, [], None) for event in events]
    assert query(empty_db, "SELECT count(*) FROM email_deliveries") == [(0,)]


def test_downgrade_de_destinatarios_sin_cambios(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, NOTIFICATION_RECIPIENTS)
    command.downgrade(config, NOTIFICATION_TEMPLATES)
    assert not NOTIFICATION_TABLES & tables(empty_db)
    command.upgrade(config, "head")
    command.check(config)


ADMIN_ROW = (
    "INSERT INTO users (id, name, email, password_hash, role, is_active, created_at)"
    " VALUES (1, 'Admin', 'admin@ultrasist.com.mx', 'x', 'ADMIN', true, now())"
)


@pytest.mark.parametrize(
    "statements",
    [
        [
            "INSERT INTO email_deliveries (event, status, to_addresses, cc_addresses, transport, message_id,"
            " created_at) VALUES (NULL, 'SENT', '{a@b.mx}', '{}', 'file', '<x@portal.local>', now())"
        ],
        [
            ADMIN_ROW,
            "UPDATE notification_copies SET addresses = '{a@b.mx}', updated_by = 1 WHERE event = 'INVOICE_REJECTED'",
        ],
        [ADMIN_ROW, "UPDATE notification_mailboxes SET addresses = '{a@b.mx}', updated_by = 1"],
    ],
)
def test_downgrade_de_destinatarios_con_datos(empty_db, statements):
    config = alembic_config(empty_db)
    command.upgrade(config, NOTIFICATION_RECIPIENTS)
    for sql in statements:
        execute(empty_db, sql)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, NOTIFICATION_TEMPLATES)
    assert NOTIFICATION_TABLES <= tables(empty_db)
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [(NOTIFICATION_RECIPIENTS,)]


SUPPLIER_CREDENTIALS = "0006_supplier_credentials"


def test_downgrade_de_credenciales_sin_uso(empty_db):
    config = alembic_config(empty_db)
    command.upgrade(config, SUPPLIER_CREDENTIALS)
    command.downgrade(config, NOTIFICATION_RECIPIENTS)
    assert query(empty_db, "SELECT count(*) FROM notification_templates") == [(4,)]
    with pytest.raises(IntegrityError, match='violates check constraint "notificationevent"'):
        execute(
            empty_db,
            "INSERT INTO email_deliveries (event, status, to_addresses, cc_addresses, transport, message_id,"
            " created_at) VALUES ('SUPPLIER_CREDENTIALS', 'SENT', '{a@b.mx}', '{}', 'file', '<x@p>', now())",
        )
    command.upgrade(config, "head")
    command.check(config)


@pytest.mark.parametrize(
    "sql",
    [
        "UPDATE notification_templates SET version = 2 WHERE event = 'SUPPLIER_CREDENTIALS'",
        "INSERT INTO email_deliveries (event, status, to_addresses, cc_addresses, transport, message_id, created_at)"
        " VALUES ('SUPPLIER_CREDENTIALS', 'SENT', '{a@b.mx}', '{}', 'file', '<x@portal.local>', now())",
    ],
)
def test_downgrade_de_credenciales_en_uso(empty_db, sql):
    config = alembic_config(empty_db)
    command.upgrade(config, SUPPLIER_CREDENTIALS)
    execute(empty_db, sql)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, NOTIFICATION_RECIPIENTS)
    assert query(empty_db, "SELECT version_num FROM alembic_version") == [(SUPPLIER_CREDENTIALS,)]
    assert query(empty_db, "SELECT count(*) FROM notification_templates") == [(5,)]
