import re
import sqlite3
from pathlib import Path

import pytest
from alembic import command

from tests.conftest import ROOT, alembic_config

VERSIONS = ROOT / "alembic" / "versions"


@pytest.fixture()
def empty_db(tmp_path) -> tuple[str, Path]:
    path = tmp_path / "migraciones.db"
    return f"sqlite:///{path.as_posix()}", path


def tables(path: Path) -> set[str]:
    with sqlite3.connect(path) as connection:
        rows = connection.execute("SELECT name FROM sqlite_master WHERE type = 'table'").fetchall()
    return {name for (name,) in rows} - {"alembic_version"}


def test_upgrade_head_coincide_con_los_modelos(empty_db):
    url, path = empty_db
    config = alembic_config(url)
    command.upgrade(config, "head")
    command.check(config)  # lanza AutogenerateDiffsDetected si modelos y migraciones difieren
    assert {
        "users",
        "suppliers",
        "contracts",
        "invoices",
        "documents",
        "validation_results",
        "audit_logs",
        "reviews",
    } <= tables(path)


def test_downgrade_de_la_revision_inicial_no_destruye_datos(empty_db):
    url, path = empty_db
    config = alembic_config(url)
    command.upgrade(config, "0001_initial")
    before = tables(path)
    with pytest.raises(NotImplementedError, match="Restaure un respaldo"):
        command.downgrade(config, "base")
    assert tables(path) == before


def test_revisiones_explicitas_sin_create_all_ni_modelos():
    revisions = list(VERSIONS.glob("*.py"))
    assert revisions
    for revision in revisions:
        source = revision.read_text(encoding="utf-8")
        for forbidden in ("create_all", "drop_all", "app.models"):
            assert forbidden not in source, f"{revision.name} contiene {forbidden}"
    assert "op.create_table" in (VERSIONS / "0001_initial.py").read_text(encoding="utf-8")


# --- Migracion 0004 sobre datos del esquema anterior -------------------------------------------------------

LEGACY = """
INSERT INTO suppliers (id, business_name, rfc, supplier_type, email, status, confidentiality_agreement,
    economic_proposal, created_at, updated_at)
    VALUES (1, 'Proveedor', 'TIC210101ABC', 'PERSONA_MORAL', 'p@x.mx', 'ACTIVE', 1, 1, '2026-09-01', '2026-09-01');
INSERT INTO users (id, name, email, password_hash, role, supplier_id, is_active, created_at) VALUES
    (1, 'Admin', 'admin@x.mx', 'h', 'ADMIN', NULL, 1, '2026-09-01 10:00:00'),
    (2, 'Prov', 'prov@x.mx', 'h', 'PROVIDER', 1, 1, '2026-09-01 10:00:00');
INSERT INTO contracts (id, supplier_id, project_name, project_leader, authorized_technology, authorized_amount,
    currency, start_date, end_date, status)
    VALUES (1, 1, 'P', 'L', 'T', 100000.10, 'MXN', '2026-01-01', '2026-12-31', 'ACTIVE');
INSERT INTO invoices (id, internal_folio, supplier_id, uploaded_by, contract_id, invoice_number, uuid, service_period,
    project_name, subtotal, tax, total, currency, status, validation_score, created_at) VALUES
    (1, 'FAC-2026-00001', 1, 2, 1, 'A', 'U-1', '08/2026', 'P', 100000.0, 16000.0, 116000.0, 'MXN', 'PREVALIDATED', 95,
     '2026-08-20 12:00:00'),
    (2, 'FAC-2026-00002', 1, 2, 1, 'B', 'U-2', '08/2026', 'P', 1064.28, 170.28, 1234.56, 'MXN', 'ACCEPTED', 80,
     '2026-08-21 12:00:00');
INSERT INTO documents (id, invoice_id, supplier_id, document_type, original_filename, stored_filename, path, mime_type,
    file_size, sha256, uploaded_at, uploaded_by, processing_status, is_current) VALUES
    (1, NULL, 1, 'TAX_STATUS', 'a.txt', 'demo_962e8155a8.txt',
     'C:\\Users\\jobhd\\Desktop\\Ultrasist\\storage\\suppliers\\1\\demo_962e8155a8.txt', 'text/plain', 1, 'x',
     '2026-09-01', 2, 'PROCESSED', 1),
    (2, 1, 1, 'INVOICE_PDF', 'f.pdf', 'ab12.pdf', '/home/dev/portal/storage/invoices/1/ab12.pdf', 'application/pdf',
     1, 'x', '2026-09-01', 2, 'PROCESSED', 1);
INSERT INTO validation_results (id, invoice_id, rule_code, category, status, severity, confidence, message, created_at)
    VALUES (1, 1, 'SEM-001', 'SEM', 'PASS', 'WARNING', 0.93, 'ok', '2026-09-01'),
           (2, 1, 'FIN-001', 'FIN', 'PASS', 'CRITICAL', NULL, 'ok', '2026-09-01');
INSERT INTO reviews (id, invoice_id, reviewer_id, decision, comments, created_at)
    VALUES (1, 2, 1, 'ACCEPTED', 'ok', '2026-09-02');
INSERT INTO audit_logs (id, user_id, action, entity, timestamp) VALUES (1, 1, 'DEMO', 'Invoice', '2026-09-01');
"""
DOMAIN_TABLES = (
    "suppliers",
    "users",
    "contracts",
    "invoices",
    "documents",
    "validation_results",
    "reviews",
    "audit_logs",
)


def legacy_db(empty_db, extra_sql: str = ""):
    url, path = empty_db
    config = alembic_config(url)
    command.upgrade(config, "0001_initial")
    with sqlite3.connect(path) as connection:
        connection.executescript(LEGACY + extra_sql)
    return config, path


def query(path: Path, sql: str) -> list:
    with sqlite3.connect(path) as connection:
        return connection.execute(sql).fetchall()


def test_actualizacion_de_una_base_existente_conserva_los_datos(empty_db):
    config, path = legacy_db(empty_db)
    before = {table: query(path, f"SELECT count(*) FROM {table}")[0][0] for table in DOMAIN_TABLES}
    command.upgrade(config, "head")
    command.check(config)
    assert {table: query(path, f"SELECT count(*) FROM {table}")[0][0] for table in DOMAIN_TABLES} == before
    assert query(
        path, "SELECT subtotal_cents, tax_cents, total_cents, typeof(total_cents) FROM invoices ORDER BY id"
    ) == [
        (10000000, 1600000, 11600000, "integer"),
        (106428, 17028, 123456, "integer"),
    ]
    assert query(path, "SELECT authorized_amount_cents FROM contracts") == [(10000010,)]
    assert query(path, "SELECT confidence_bp FROM validation_results ORDER BY id") == [(9300,), (None,)]
    assert query(path, "SELECT path FROM documents ORDER BY id") == [
        ("suppliers/1/demo_962e8155a8.txt",),
        ("invoices/1/ab12.pdf",),
    ]
    assert "ON DELETE RESTRICT" in query(path, "SELECT sql FROM sqlite_master WHERE name = 'documents'")[0][0]
    assert query(path, "PRAGMA foreign_key_check") == []


@pytest.mark.parametrize(
    ("extra_sql", "reason"),
    [
        ("UPDATE invoices SET uuid = 'U-1' WHERE id = 2;", "UUID U-1 duplicado en facturas 1,2"),
        ("UPDATE invoices SET invoice_number = 'A' WHERE id = 2;", "numero 'A' duplicado"),
        ("UPDATE invoices SET status = 'APROBADA' WHERE id = 2;", "invoices.status con valor fuera de catalogo"),
        ("UPDATE invoices SET total = 10.005 WHERE id = 2;", "invoices.total con mas de 2 decimales"),
        ("UPDATE documents SET path = '/otra/ruta/x.pdf' WHERE id = 2;", "no se puede derivar una ruta relativa"),
    ],
)
def test_precondiciones_abortan_sin_cambios(empty_db, extra_sql, reason):
    config, path = legacy_db(empty_db, extra_sql)
    with pytest.raises(RuntimeError, match=re.escape(reason)):
        command.upgrade(config, "head")
    assert query(path, "SELECT version_num FROM alembic_version") == [("0003_login_attempts",)]
    assert query(path, "SELECT subtotal FROM invoices WHERE id = 1") == [(100000.0,)]
    assert "subtotal_cents" not in query(path, "SELECT sql FROM sqlite_master WHERE name = 'invoices'")[0][0]
    command.upgrade(config, "0003_login_attempts")  # el esquema previo sigue integro y reanudable
