sonar.projectKey=portal-facturas
sonar.projectName=Portal de Facturas
sonar.sources=app,infra/keycloak/themes
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=app/static/vendor/**,infra/keycloak/themes/**/vendor/**
